
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "pqwordshelper"
version = "0.1.0"
edition = "2021"

[dependencies]
fs_extra = "1.3.0"


